// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AISettings() {
  return window['go']['main']['App']['AISettings']();
}

export function AddEffect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddEffect'](arg1, arg2, arg3, arg4);
}

export function AddMap(arg1, arg2) {
  return window['go']['main']['App']['AddMap'](arg1, arg2);
}

export function AddMonster(arg1, arg2) {
  return window['go']['main']['App']['AddMonster'](arg1, arg2);
}

export function AddPin(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddPin'](arg1, arg2, arg3, arg4);
}

export function AddPlace(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddPlace'](arg1, arg2, arg3, arg4, arg5);
}

export function AddSRDItems() {
  return window['go']['main']['App']['AddSRDItems']();
}

export function AddToEncounter(arg1) {
  return window['go']['main']['App']['AddToEncounter'](arg1);
}

export function AddXP(arg1, arg2) {
  return window['go']['main']['App']['AddXP'](arg1, arg2);
}

export function AdjustCoins(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdjustCoins'](arg1, arg2, arg3);
}

export function ApplyDamage(arg1, arg2) {
  return window['go']['main']['App']['ApplyDamage'](arg1, arg2);
}

export function ApplyHeal(arg1, arg2) {
  return window['go']['main']['App']['ApplyHeal'](arg1, arg2);
}

export function Attack(arg1, arg2, arg3) {
  return window['go']['main']['App']['Attack'](arg1, arg2, arg3);
}

export function AttackAll(arg1, arg2, arg3) {
  return window['go']['main']['App']['AttackAll'](arg1, arg2, arg3);
}

export function Bestiary() {
  return window['go']['main']['App']['Bestiary']();
}

export function Cast(arg1, arg2, arg3) {
  return window['go']['main']['App']['Cast'](arg1, arg2, arg3);
}

export function CastSpell(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CastSpell'](arg1, arg2, arg3, arg4);
}

export function Catalog() {
  return window['go']['main']['App']['Catalog']();
}

export function Characters() {
  return window['go']['main']['App']['Characters']();
}

export function Check(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Check'](arg1, arg2, arg3, arg4, arg5);
}

export function ClearLog() {
  return window['go']['main']['App']['ClearLog']();
}

export function ClearMonsters() {
  return window['go']['main']['App']['ClearMonsters']();
}

export function CreateCharacter(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateCharacter'](arg1, arg2, arg3, arg4, arg5);
}

export function DeathSave(arg1) {
  return window['go']['main']['App']['DeathSave'](arg1);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['App']['DeleteCharacter'](arg1);
}

export function DeleteLibraryItem(arg1) {
  return window['go']['main']['App']['DeleteLibraryItem'](arg1);
}

export function DeleteMap(arg1) {
  return window['go']['main']['App']['DeleteMap'](arg1);
}

export function DeleteMonster(arg1) {
  return window['go']['main']['App']['DeleteMonster'](arg1);
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function DeleteSpellTemplate(arg1) {
  return window['go']['main']['App']['DeleteSpellTemplate'](arg1);
}

export function DropConcentration(arg1) {
  return window['go']['main']['App']['DropConcentration'](arg1);
}

export function Encounter() {
  return window['go']['main']['App']['Encounter']();
}

export function EncounterTreasure(arg1) {
  return window['go']['main']['App']['EncounterTreasure'](arg1);
}

export function EndEncounter(arg1) {
  return window['go']['main']['App']['EndEncounter'](arg1);
}

export function ExportSession() {
  return window['go']['main']['App']['ExportSession']();
}

export function GenerateDungeon(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateDungeon'](arg1, arg2, arg3, arg4);
}

export function GenerateWorld(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateWorld'](arg1, arg2, arg3, arg4, arg5);
}

export function GetFog(arg1) {
  return window['go']['main']['App']['GetFog'](arg1);
}

export function GetMapImage(arg1) {
  return window['go']['main']['App']['GetMapImage'](arg1);
}

export function GiveItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['GiveItem'](arg1, arg2, arg3);
}

export function GiveLoot(arg1, arg2, arg3) {
  return window['go']['main']['App']['GiveLoot'](arg1, arg2, arg3);
}

export function GiveSpellTemplate(arg1, arg2) {
  return window['go']['main']['App']['GiveSpellTemplate'](arg1, arg2);
}

export function ImportAzgaar(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImportAzgaar'](arg1, arg2, arg3, arg4);
}

export function ImportOnePageDungeon(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportOnePageDungeon'](arg1, arg2, arg3);
}

export function ItemLibrary() {
  return window['go']['main']['App']['ItemLibrary']();
}

export function LegendaryAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['LegendaryAction'](arg1, arg2, arg3);
}

export function LoadSnapshot(arg1) {
  return window['go']['main']['App']['LoadSnapshot'](arg1);
}

export function Log() {
  return window['go']['main']['App']['Log']();
}

export function Maps() {
  return window['go']['main']['App']['Maps']();
}

export function MonsterTurn() {
  return window['go']['main']['App']['MonsterTurn']();
}

export function NextTurn() {
  return window['go']['main']['App']['NextTurn']();
}

export function PopulateMap(arg1, arg2, arg3) {
  return window['go']['main']['App']['PopulateMap'](arg1, arg2, arg3);
}

export function PopulatePlace(arg1, arg2, arg3) {
  return window['go']['main']['App']['PopulatePlace'](arg1, arg2, arg3);
}

export function QuickSave() {
  return window['go']['main']['App']['QuickSave']();
}

export function RecognizeMap(arg1, arg2) {
  return window['go']['main']['App']['RecognizeMap'](arg1, arg2);
}

export function RemoveEffect(arg1, arg2) {
  return window['go']['main']['App']['RemoveEffect'](arg1, arg2);
}

export function RemoveFromEncounter(arg1) {
  return window['go']['main']['App']['RemoveFromEncounter'](arg1);
}

export function RemovePin(arg1, arg2) {
  return window['go']['main']['App']['RemovePin'](arg1, arg2);
}

export function RemovePlace(arg1, arg2) {
  return window['go']['main']['App']['RemovePlace'](arg1, arg2);
}

export function RenameMap(arg1, arg2) {
  return window['go']['main']['App']['RenameMap'](arg1, arg2);
}

export function Rest(arg1, arg2) {
  return window['go']['main']['App']['Rest'](arg1, arg2);
}

export function RestAll(arg1) {
  return window['go']['main']['App']['RestAll'](arg1);
}

export function Revive(arg1) {
  return window['go']['main']['App']['Revive'](arg1);
}

export function Roll(arg1, arg2) {
  return window['go']['main']['App']['Roll'](arg1, arg2);
}

export function RollTreasure(arg1, arg2) {
  return window['go']['main']['App']['RollTreasure'](arg1, arg2);
}

export function SaveLibraryItem(arg1) {
  return window['go']['main']['App']['SaveLibraryItem'](arg1);
}

export function SaveMonster(arg1) {
  return window['go']['main']['App']['SaveMonster'](arg1);
}

export function SaveSnapshot(arg1) {
  return window['go']['main']['App']['SaveSnapshot'](arg1);
}

export function SaveSpellTemplate(arg1) {
  return window['go']['main']['App']['SaveSpellTemplate'](arg1);
}

export function SetAISettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAISettings'](arg1, arg2, arg3);
}

export function SetCoins(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCoins'](arg1, arg2, arg3);
}

export function SetEncounterOptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetEncounterOptions'](arg1, arg2, arg3);
}

export function SetFog(arg1, arg2) {
  return window['go']['main']['App']['SetFog'](arg1, arg2);
}

export function SetMapGrid(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMapGrid'](arg1, arg2, arg3);
}

export function Snapshots() {
  return window['go']['main']['App']['Snapshots']();
}

export function SpawnInBattle(arg1, arg2) {
  return window['go']['main']['App']['SpawnInBattle'](arg1, arg2);
}

export function SpellLibrary() {
  return window['go']['main']['App']['SpellLibrary']();
}

export function SplitCoins(arg1, arg2) {
  return window['go']['main']['App']['SplitCoins'](arg1, arg2);
}

export function StartEncounter(arg1) {
  return window['go']['main']['App']['StartEncounter'](arg1);
}

export function ToggleReaction(arg1) {
  return window['go']['main']['App']['ToggleReaction'](arg1);
}

export function TransferItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TransferItem'](arg1, arg2, arg3, arg4);
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}

export function UpdateCharacter(arg1) {
  return window['go']['main']['App']['UpdateCharacter'](arg1);
}

export function UpdatePlace(arg1, arg2) {
  return window['go']['main']['App']['UpdatePlace'](arg1, arg2);
}

export function UseAbility(arg1, arg2, arg3) {
  return window['go']['main']['App']['UseAbility'](arg1, arg2, arg3);
}

export function UseFeature(arg1, arg2) {
  return window['go']['main']['App']['UseFeature'](arg1, arg2);
}

export function UseSpecial(arg1) {
  return window['go']['main']['App']['UseSpecial'](arg1);
}

export function UseSpecialAt(arg1, arg2) {
  return window['go']['main']['App']['UseSpecialAt'](arg1, arg2);
}

export function Warning() {
  return window['go']['main']['App']['Warning']();
}
