// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {combat} from '../models';
import {bestiary} from '../models';
import {rules} from '../models';
import {treasure} from '../models';
import {model} from '../models';

export function AddEffect(arg1:string,arg2:string,arg3:number,arg4:string):Promise<main.CharView>;

export function AddMap(arg1:string,arg2:string):Promise<main.MapInfo>;

export function AddMonster(arg1:string,arg2:number):Promise<Array<main.CharView>>;

export function AddPin(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function AddPlace(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<main.MapInfo>;

export function AddSRDItems():Promise<number>;

export function AddToEncounter(arg1:Array<string>):Promise<combat.Encounter>;

export function AddXP(arg1:string,arg2:number):Promise<main.CharView>;

export function AdjustCoins(arg1:string,arg2:string,arg3:number):Promise<main.CharView>;

export function ApplyDamage(arg1:string,arg2:number):Promise<main.CharView>;

export function ApplyHeal(arg1:string,arg2:number):Promise<main.CharView>;

export function Attack(arg1:string,arg2:number,arg3:string):Promise<main.EncounterView>;

export function AttackAll(arg1:string,arg2:number,arg3:string):Promise<main.MultiView>;

export function Bestiary():Promise<Array<bestiary.Monster>>;

export function Cast(arg1:string,arg2:number,arg3:number):Promise<main.CharView>;

export function CastSpell(arg1:number,arg2:number,arg3:Array<string>,arg4:string):Promise<combat.Encounter>;

export function Catalog():Promise<Array<rules.Catalog>>;

export function Characters():Promise<Array<main.CharView>>;

export function Check(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<main.RollView>;

export function ClearLog():Promise<void>;

export function ClearMonsters():Promise<number>;

export function CreateCharacter(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.CharView>;

export function DeathSave(arg1:string):Promise<main.CharView>;

export function DeleteCharacter(arg1:string):Promise<void>;

export function DeleteLibraryItem(arg1:string):Promise<void>;

export function DeleteMap(arg1:string):Promise<void>;

export function DeleteMonster(arg1:string):Promise<void>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function DeleteSpellTemplate(arg1:string):Promise<void>;

export function DropConcentration(arg1:string):Promise<combat.Encounter>;

export function Encounter():Promise<combat.Encounter>;

export function EncounterTreasure(arg1:boolean):Promise<treasure.Treasure>;

export function EndEncounter(arg1:boolean):Promise<number>;

export function ExportSession():Promise<string>;

export function GenerateDungeon(arg1:string,arg2:number,arg3:number,arg4:number):Promise<main.MapInfo>;

export function GenerateWorld(arg1:string,arg2:number,arg3:Array<string>,arg4:number,arg5:string,arg6:string):Promise<main.MapInfo>;

export function GetFog(arg1:string):Promise<string>;

export function GetMapImage(arg1:string):Promise<string>;

export function GiveItem(arg1:string,arg2:string,arg3:number):Promise<main.CharView>;

export function GiveLoot(arg1:string,arg2:model.Item,arg3:number):Promise<main.CharView>;

export function GiveSpellTemplate(arg1:string,arg2:string):Promise<main.CharView>;

export function ItemLibrary():Promise<Array<model.Item>>;

export function LegendaryAction(arg1:string,arg2:string,arg3:string):Promise<main.LegendaryView>;

export function LoadSnapshot(arg1:string):Promise<void>;

export function Log():Promise<Array<string>>;

export function Maps():Promise<Array<main.MapInfo>>;

export function MonsterTurn():Promise<main.MonsterTurnView>;

export function NextTurn():Promise<combat.Encounter>;

export function PopulateMap(arg1:string,arg2:number,arg3:boolean):Promise<main.MapInfo>;

export function PopulatePlace(arg1:string,arg2:string,arg3:number):Promise<main.MapInfo>;

export function QuickSave():Promise<main.SnapshotInfo>;

export function RemoveEffect(arg1:string,arg2:number):Promise<main.CharView>;

export function RemoveFromEncounter(arg1:string):Promise<combat.Encounter>;

export function RemovePin(arg1:string,arg2:number):Promise<void>;

export function RemovePlace(arg1:string,arg2:string):Promise<main.MapInfo>;

export function RenameMap(arg1:string,arg2:string):Promise<void>;

export function Rest(arg1:string,arg2:string):Promise<main.CharView>;

export function RestAll(arg1:string):Promise<void>;

export function Revive(arg1:string):Promise<main.CharView>;

export function Roll(arg1:string,arg2:string):Promise<main.RollView>;

export function RollTreasure(arg1:Array<string>,arg2:boolean):Promise<treasure.Treasure>;

export function SaveLibraryItem(arg1:model.Item):Promise<model.Item>;

export function SaveMonster(arg1:bestiary.Monster):Promise<bestiary.Monster>;

export function SaveSnapshot(arg1:string):Promise<void>;

export function SaveSpellTemplate(arg1:model.SpellTemplate):Promise<model.SpellTemplate>;

export function SetCoins(arg1:string,arg2:string,arg3:number):Promise<main.CharView>;

export function SetEncounterOptions(arg1:boolean,arg2:boolean,arg3:boolean):Promise<combat.Encounter>;

export function SetFog(arg1:string,arg2:string):Promise<void>;

export function SetMapGrid(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Snapshots():Promise<Array<main.SnapshotInfo>>;

export function SpawnInBattle(arg1:string,arg2:number):Promise<combat.Encounter>;

export function SpellLibrary():Promise<Array<model.SpellTemplate>>;

export function SplitCoins(arg1:Array<string>,arg2:Record<string, number>):Promise<Array<main.CharView>>;

export function StartEncounter(arg1:Array<string>):Promise<combat.Encounter>;

export function ToggleReaction(arg1:string):Promise<combat.Encounter>;

export function TransferItem(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<main.CharView>>;

export function Undo():Promise<void>;

export function UpdateCharacter(arg1:model.Character):Promise<main.CharView>;

export function UpdatePlace(arg1:string,arg2:model.Place):Promise<main.MapInfo>;

export function UseAbility(arg1:string,arg2:string,arg3:string):Promise<main.CharView>;

export function UseFeature(arg1:string,arg2:string):Promise<main.CharView>;

export function UseSpecial(arg1:string):Promise<combat.Encounter>;

export function UseSpecialAt(arg1:string,arg2:string):Promise<combat.Encounter>;

export function Warning():Promise<string>;
